import { db } from '../src/lib/db';
import { createHash } from 'crypto';

// Dynamic tenant lookup
let TENANTS: { id: string; name: string }[] = [];

async function loadTenants() {
  TENANTS = await db.tenant.findMany({ select: { id: true, name: true } });
  console.log(`Found ${TENANTS.length} tenants:`, TENANTS.map(t => t.name).join(', '));
}

const STATES = ['Lagos', 'Abuja FCT', 'Kano', 'Rivers', 'Enugu', 'Borno', 'Oyo', 'Delta', 'Kaduna', 'Anambra'];
const PARTIES = ['APC', 'PDP', 'LP', 'NNPP', 'SDP'];
const PARTY_COLORS: Record<string, string> = { APC: '#00A651', PDP: '#E21A2B', LP: '#008751', NNPP: '#FF6B00', SDP: '#6B7280' };

function randomInt(min: number, max: number) { return Math.floor(Math.random() * (max - min + 1)) + min; }
function randomFloat(min: number, max: number, dec = 2) { return parseFloat((Math.random() * (max - min) + min).toFixed(dec)); }
function pick<T>(arr: T[]): T { return arr[Math.floor(Math.random() * arr.length)]; }

function generatePartyResults(total: number) {
  let remaining = total;
  const results: { party: string; votes: number }[] = [];
  for (let i = 0; i < PARTIES.length - 1; i++) {
    const share = randomInt(5, Math.floor(remaining * 0.5));
    results.push({ party: PARTIES[i], votes: share });
    remaining -= share;
  }
  results.push({ party: PARTIES[PARTIES.length - 1], votes: remaining });
  return results.sort((a, b) => b.votes - a.votes);
}

// ═══════════════════════════════════════════════════════════
// PVT Submissions
// ═══════════════════════════════════════════════════════════
async function seedPvt() {
  console.log('Seeding PVT submissions...');

  for (const tenant of TENANTS) {
    const elections = await db.election.findMany({ where: { tenantId: tenant.id }, select: { id: true } });
    if (!elections.length) continue;
    const electionId = elections[0].id;

    const units = await db.pollingUnit.findMany({
      where: { electionId },
      select: { id: true, state: true, lga: true, registeredVoters: true },
    });
    const users = await db.user.findMany({ where: { tenantId: tenant.id, role: 'FIELD_AGENT' }, select: { id: true } });

    const count = Math.min(units.length, 40);
    const selected = units.sort(() => Math.random() - 0.5).slice(0, count);

    for (let i = 0; i < selected.length; i++) {
      const unit = selected[i];
      const accredited = Math.floor(unit.registeredVoters * randomFloat(0.5, 0.9));
      const totalVotes = Math.floor(accredited * randomFloat(0.6, 0.95));
      const partyResults = generatePartyResults(totalVotes);
      const validVotes = totalVotes - randomInt(0, Math.floor(totalVotes * 0.05));
      const hash = createHash('sha256').update(JSON.stringify(partyResults)).digest('hex');

      await db.pvtSubmission.create({
        data: {
          tenantId: tenant.id,
          electionId,
          pollingUnitId: unit.id,
          submittedById: users[i % users.length]?.id || 'unknown',
          partyResults: JSON.stringify(partyResults),
          accreditedVoters: accredited,
          totalValidVotes: validVotes,
          rejectedBallots: totalVotes - validVotes,
          totalVotesCast: totalVotes,
          bvasSerialNumber: `BVAS-${unit.state.substring(0, 3)}-${randomInt(1000, 9999)}`,
          source: pick(['MOBILE', 'WHATSAPP', 'PAPER']),
          verificationHash: hash,
          isVerified: Math.random() > 0.4,
          verifiedById: Math.random() > 0.4 ? (users[0]?.id || null) : null,
          verifiedAt: Math.random() > 0.4 ? new Date(Date.now() - randomInt(10, 120) * 60000) : null,
          submittedAt: new Date(Date.now() - randomInt(5, 300) * 60000),
        },
      });
    }
    console.log(`  ${tenant.name}: ${count} PVT submissions`);
  }
}

// ═══════════════════════════════════════════════════════════
// Result Comparisons (auto-generated by API, but seed some)
// ═══════════════════════════════════════════════════════════
async function seedComparisons() {
  console.log('Seeding result comparisons...');

  for (const tenant of TENANTS) {
    const elections = await db.election.findMany({ where: { tenantId: tenant.id }, select: { id: true } });
    if (!elections.length) continue;

    const pvts = await db.pvtSubmission.findMany({
      where: { tenantId: tenant.id, electionId: elections[0].id },
      select: { id: true, pollingUnitId: true, partyResults: true, totalVotesCast: true },
    });

    const officials = await db.electionResult.findMany({
      where: { tenantId: tenant.id },
      select: { id: true, pollingUnitId: true, partyResults: true, totalVotesCast: true },
    });

    const officialByUnit = new Map(officials.map(o => [o.pollingUnitId, o]));
    let created = 0;

    for (const pvt of pvts) {
      const official = officialByUnit.get(pvt.pollingUnitId);
      if (!official) continue;

      const pvtResults: { party: string; votes: number }[] = JSON.parse(pvt.partyResults || '[]');
      const offResults: { party: string; votes: number }[] = JSON.parse(official.partyResults || '[]');

      const partyDeltas = pvtResults.map(pr => {
        const off = offResults.find(o => o.party === pr.party);
        const offVotes = off?.votes || 0;
        const delta = offVotes - pr.votes;
        return { party: pr.party, pvtVotes: pr.votes, officialVotes: offVotes, delta, deltaPct: pr.votes > 0 ? Math.abs(delta / pr.votes) * 100 : 0 };
      });

      const totalDelta = official.totalVotesCast - pvt.totalVotesCast;
      const deltaPct = pvt.totalVotesCast > 0 ? Math.abs(totalDelta / pvt.totalVotesCast) * 100 : 0;
      const isAnomaly = deltaPct > 5;

      await db.resultComparison.create({
        data: {
          tenantId: tenant.id,
          electionId: elections[0].id,
          pollingUnitId: pvt.pollingUnitId,
          pvtSubmissionId: pvt.id,
          officialResultId: official.id,
          partyDeltas: JSON.stringify(partyDeltas),
          totalPvtVotes: pvt.totalVotesCast,
          totalOfficialVotes: official.totalVotesCast,
          totalDelta,
          deltaPct,
          isAnomaly,
          anomalyReason: isAnomaly ? (deltaPct > 10 ? 'exceeds_10pct' : 'exceeds_5pct') : null,
        },
      });
      created++;
    }
    console.log(`  ${tenant.name}: ${created} comparisons`);
  }
}

// ═══════════════════════════════════════════════════════════
// Evidence Dossiers & Stego Scans
// ═══════════════════════════════════════════════════════════
async function seedEvidence() {
  console.log('Seeding evidence dossiers...');

  const DOSSIER_TITLES = [
    'Ballot Box Stuffing — PU 012/03/05/001 Lagos Island',
    'Voter Intimidation Video — Kano Municipal',
    'BVAS Malfunction Report — Enugu East LGA',
    'Fake INEC Press Release Detection',
    'Deepfake Audio of Party Chairman',
    'Armed Group Deployment Evidence — Borno',
    'Material Diversion Photo Series — Rivers',
    'Underage Voting Documentation — Kaduna',
    'Results Sheet Tampering Analysis — Delta',
    'Social Media Coordinated Campaign',
    'Polling Agent Assault Evidence — Oyo',
    'Vote Buying Video Compilation',
    ' Collusion Between Party Agents — Anambra',
    'Fake Police Deployment Order',
    'Multiple Voting Detection — Abuja FCT',
  ];

  const STEGO_FILES = [
    { name: 'ballot_stuffed_001.jpg', type: 'JPEG' },
    { name: 'intimidation_video.mp4', type: 'MP4' },
    { name: 'bvas_screen_capture.png', type: 'PNG' },
    { name: 'fake_inec_release.pdf.jpg', type: 'JPEG' },
    { name: 'party_chairman_audio.wav', type: 'WAV' },
    { name: 'armed_group_photo.jpg', type: 'JPEG' },
    { name: 'material_diversion_01.png', type: 'PNG' },
    { name: 'results_sheet_tampered.jpg', type: 'JPEG' },
  ];

  for (const tenant of TENANTS) {
    const incidents = await db.incident.findMany({ where: { tenantId: tenant.id }, select: { id: true } });

    for (let i = 0; i < 12; i++) {
      const isCertified = Math.random() > 0.7;
      const stegoScan = STEGO_FILES[i % STEGO_FILES.length];
      const isManip = Math.random() > 0.7;
      const manipulationTypes = ['lsb_embedding', 'exif_tamper', 'audio_stego', 'deepfake_face', 'clone_stamp'];

      const dossier = await db.evidenceDossier.create({
        data: {
          tenantId: tenant.id,
          incidentId: incidents[i % incidents.length]?.id || null,
          title: DOSSIER_TITLES[i % DOSSIER_TITLES.length],
          description: `Comprehensive evidence package for incident involving potential electoral violation. Contains ${randomInt(2, 8)} media items analyzed by AI forensic pipeline.`,
          evidenceItems: JSON.stringify([
            { type: 'photo', url: `https://s3.amazonaws.com/omnivote/evidence/${tenant.name.toLowerCase()}_${i}_1.jpg`, c2paVerified: Math.random() > 0.3, aiAnalysis: 'Image analysis shows no signs of manipulation. C2PA signature valid. Metadata consistent with capture device.' },
            { type: 'video', url: `https://s3.amazonaws.com/omnivote/evidence/${tenant.name.toLowerCase()}_${i}_2.mp4`, c2paVerified: Math.random() > 0.5, aiAnalysis: 'Video forensics: consistent frame timing, no splice artifacts detected. Audio channel shows no signs of editing.' },
          ]),
          c2paSigned: Math.random() > 0.4,
          c2paSignature: Math.random() > 0.4 ? `base64_manifest_${i}_${randomInt(1000, 9999)}` : null,
          aiSummary: `AI Analysis: Evidence credibility score ${randomInt(65, 98)}%. ${isManip ? 'WARNING: Potential manipulation detected in one or more files. Further forensic review recommended.' : 'All analyzed media passes integrity checks. No manipulation indicators found.'}`,
          aiConfidence: randomFloat(0.6, 0.98),
          status: isCertified ? 'CERTIFIED' : (Math.random() > 0.5 ? 'REVIEWED' : 'DRAFT'),
          reviewedById: isCertified ? 'sys_admin' : null,
          reviewedAt: isCertified ? new Date(Date.now() - randomInt(10, 240) * 60000) : null,
          createdAt: new Date(Date.now() - randomInt(30, 720) * 60000),
        },
      });

      // Create stego scan for each dossier
      await db.stegoScanResult.create({
        data: {
          tenantId: tenant.id,
          evidenceDossierId: dossier.id,
          fileName: stegoScan.name,
          fileType: stegoScan.type,
          fileSize: randomInt(500000, 15000000),
          fileUrl: `https://s3.amazonaws.com/omnivote/evidence/${stegoScan.name}`,
          isManipulated: isManip,
          manipulationType: isManip ? pick(manipulationTypes) : null,
          confidence: isManip ? randomFloat(0.65, 0.97) : randomFloat(0.05, 0.3),
          elaScore: randomFloat(0, 100),
          noiseAnalysis: JSON.stringify({ mean: randomFloat(10, 50), stdDev: randomFloat(5, 25), uniformity: randomFloat(0.1, 0.95) }),
          metadataDiff: isManip ? JSON.stringify({ gpsMismatch: true, timestampAnomaly: Math.random() > 0.5, softwareMismatch: false }) : null,
          scanDurationMs: randomInt(500, 5000),
          scannedAt: new Date(Date.now() - randomInt(20, 300) * 60000),
        },
      });
    }
    console.log(`  ${tenant.name}: 12 dossiers + stego scans`);
  }
}

// ═══════════════════════════════════════════════════════════
// Honeypot Units
// ═══════════════════════════════════════════════════════════
async function seedHoneypots() {
  console.log('Seeding honeypot units...');

  for (const tenant of TENANTS) {
    const elections = await db.election.findMany({ where: { tenantId: tenant.id }, select: { id: true } });
    if (!elections.length) continue;

    const units = await db.pollingUnit.findMany({
      where: { electionId: elections[0].id },
      select: { id: true, name: true, code: true, state: true, lga: true },
    });

    const trapTypes = ['GHOST_UNIT', 'TAMPER_TRAP', 'REPLAY_DETECTOR'];
    const honeypotUnits = units.sort(() => Math.random() - 0.5).slice(0, 15);

    for (let i = 0; i < honeypotUnits.length; i++) {
      const unit = honeypotUnits[i];
      const trapType = trapTypes[i % trapTypes.length];
      const expectedResults = generatePartyResults(randomInt(200, 800));
      const hasDeviation = Math.random() > 0.5;
      const deviationPct = hasDeviation ? randomFloat(5, 25) : 0;
      const officialResults = hasDeviation
        ? expectedResults.map(r => ({
            party: r.party,
            votes: Math.floor(r.votes * (1 + (deviationPct / 100) * (Math.random() > 0.5 ? 1 : -1))),
          }))
        : expectedResults.map(r => ({ party: r.party, votes: r.votes + randomInt(-5, 5) }));

      await db.honeypotUnit.create({
        data: {
          tenantId: tenant.id,
          pollingUnitId: unit.id,
          name: `[HONEYPOT] ${unit.name}`,
          state: unit.state,
          lga: unit.lga,
          trapType,
          expectedResults: JSON.stringify(expectedResults),
          officialResults: JSON.stringify(officialResults),
          deviationDetected: hasDeviation,
          deviationPct,
          alertTriggered: hasDeviation && deviationPct > 10,
          isActive: true,
          createdAt: new Date(Date.now() - randomInt(60, 480) * 60000),
        },
      });
    }
    console.log(`  ${tenant.name}: ${honeypotUnits.length} honeypots`);
  }
}

// ═══════════════════════════════════════════════════════════
// Flashpoint Forecasts
// ═══════════════════════════════════════════════════════════
async function seedFlashpoints() {
  console.log('Seeding flashpoint forecasts...');

  const FACTORS = [
    'historical_violence', 'high_unemployment', 'ethnic_tensions', 'political_polarization',
    'security_force_absence', 'youth_demographics', 'weapon_proliferation', 'inflammatory_rhetoric',
    'past_election_disputes', 'economic_hardship', 'religious_tensions', 'drug_abuse',
  ];

  for (const tenant of TENANTS) {
    const statesToUse = STATES.slice(0, 7); // Use 7 states per tenant

    for (const state of statesToUse) {
      const violence = randomFloat(0.1, 0.95);
      const intimidation = randomFloat(0.1, 0.85);
      const logistics = randomFloat(0.05, 0.6);
      const overall = (violence * 0.4 + intimidation * 0.35 + logistics * 0.25);
      const riskLevel = overall > 0.7 ? 'CRITICAL' : overall > 0.5 ? 'HIGH' : overall > 0.3 ? 'MEDIUM' : 'LOW';

      // Build 7-day forecast
      const forecast = [];
      for (let d = 0; d < 7; d++) {
        const date = new Date(Date.now() + d * 86400000);
        const dayFactor = d === 0 ? 1.0 : 1.0 + (d - 3) * 0.05; // election day highest
        forecast.push({
          date: date.toISOString().split('T')[0],
          overall: Math.min(1, parseFloat((overall * dayFactor + randomFloat(-0.05, 0.05)).toFixed(2))),
          violence: Math.min(1, parseFloat((violence * dayFactor + randomFloat(-0.05, 0.05)).toFixed(2))),
          intimidation: Math.min(1, parseFloat((intimidation * dayFactor + randomFloat(-0.05, 0.05)).toFixed(2))),
          logistics: Math.min(1, parseFloat((logistics * dayFactor + randomFloat(-0.03, 0.03)).toFixed(2))),
        });
      }

      // Pick 3-5 contributing factors
      const shuffled = [...FACTORS].sort(() => Math.random() - 0.5);
      const contributingFactors = shuffled.slice(0, randomInt(3, 5));

      await db.flashpointForecast.create({
        data: {
          tenantId: tenant.id,
          state,
          lga: null,
          riskScores: JSON.stringify({ violence, intimidation, logistics, overall: parseFloat(overall.toFixed(2)) }),
          riskLevel,
          forecast: JSON.stringify(forecast),
          contributingFactors: JSON.stringify(contributingFactors),
          aiModel: 'ensemble_v2',
          confidence: randomFloat(0.6, 0.95),
          generatedAt: new Date(),
          expiresAt: new Date(Date.now() + 24 * 3600000),
        },
      });
    }

    // Create 3 wargame scenarios
    const scenarios = [
      {
        title: 'Mass Ballot Box Snatching — Lagos Island',
        description: 'Simulation of coordinated ballot box theft across 15 polling units in Lagos Island LGA during peak voting hours.',
        parameters: { triggerType: 'BALLOT_THEFT', affectedStates: ['Lagos'], severity: 'HIGH', playerRole: 'BLUE_TEAM' },
        steps: [
          { step: 1, description: 'Initial report of armed men at PU 001', action: 'Deploy rapid response team', outcome: 'Team arrives in 12 minutes, situation contained' },
          { step: 2, description: 'Second incident at PU 005, 2km away', action: 'Request additional security deployment', outcome: 'Backup delayed by traffic, 3 boxes taken' },
          { step: 3, description: 'Social media misinformation campaign begins', action: 'Activate counter-narrative via mobilization engine', outcome: 'Counter-messages reach 50K people in 30 minutes' },
        ],
      },
      {
        title: 'INEC Server Outage — Nationwide BVAS Failure',
        description: 'Simulate complete BVAS connectivity failure affecting accreditation across multiple states simultaneously.',
        parameters: { triggerType: 'TECH_FAILURE', affectedStates: STATES.slice(0, 5), severity: 'CRITICAL', playerRole: 'RED_TEAM' },
        steps: [
          { step: 1, description: 'BVAS devices begin failing to connect in 3 states', action: 'INEC technical team diagnoses network issue', outcome: 'Identified as DDoS attack on INEC servers' },
          { step: 2, description: 'Opposition parties demand election postponement', action: 'Chairman addresses press conference', outcome: 'Public trust drops 15%, protests begin' },
        ],
      },
      {
        title: 'Ethnic Violence Trigger — Plateau/Kaduna Border',
        description: 'Simulate escalation from minor altercation to major inter-communal violence near polling units.',
        parameters: { triggerType: 'ETHNIC_VIOLENCE', affectedStates: ['Kaduna'], severity: 'HIGH', playerRole: 'OBSERVER' },
        steps: [
          { step: 1, description: 'Verbal altercation between two voter groups', action: 'Polling officials attempt de-escalation', outcome: 'Situation temporarily calmed' },
          { step: 2, description: 'Reinforcements arrive from both sides', action: 'Call security forces', outcome: 'Security deployed, voting suspended in 3 units' },
          { step: 3, description: 'Rumors spread on social media', action: 'Deploy fact-checking team', outcome: '5 false claims debunked, tension reduced' },
          { step: 4, description: 'Curfew imposed by state governor', action: 'Monitor compliance via field agents', outcome: '87% compliance rate, 2 violations reported' },
        ],
      },
    ];

    for (const s of scenarios) {
      const status = pick(['COMPLETED', 'RUNNING', 'DRAFT']);
      await db.wargameScenario.create({
        data: {
          tenantId: tenant.id,
          title: s.title,
          description: s.description,
          parameters: JSON.stringify(s.parameters),
          steps: JSON.stringify(s.steps),
          status,
          currentPlayerRole: s.parameters.playerRole,
          results: status === 'COMPLETED' ? JSON.stringify({ responseTime: '8min', correctActions: randomInt(2, 4), missedActions: randomInt(0, 2), score: randomInt(60, 95) }) : null,
          score: status === 'COMPLETED' ? randomInt(60, 95) : null,
          startedAt: status !== 'DRAFT' ? new Date(Date.now() - randomInt(30, 300) * 60000) : null,
          completedAt: status === 'COMPLETED' ? new Date(Date.now() - randomInt(10, 60) * 60000) : null,
          createdAt: new Date(Date.now() - randomInt(60, 720) * 60000),
        },
      });
    }
    console.log(`  ${tenant.name}: 7 forecasts + 3 wargame scenarios`);
  }
}

// ═══════════════════════════════════════════════════════════
// Accessibility / PWD Reports
// ═══════════════════════════════════════════════════════════
async function seedAccessibility() {
  console.log('Seeding accessibility reports...');

  const BARRIERS = ['no_ramp', 'stairs_only', 'no_assistive_tech', 'no_braille', 'no_sign_language', 'poor_lighting', 'narrow_doorway', 'no_accessible_toilet', 'uneven_surface', 'no_parking'];

  for (const tenant of TENANTS) {
    const elections = await db.election.findMany({ where: { tenantId: tenant.id }, select: { id: true } });
    if (!elections.length) continue;

    const units = await db.pollingUnit.findMany({
      where: { electionId: elections[0].id },
      select: { id: true, state: true },
    });
    const users = await db.user.findMany({ where: { tenantId: tenant.id, role: 'FIELD_AGENT' }, select: { id: true } });

    const count = Math.min(units.length, 25);
    const selected = units.sort(() => Math.random() - 0.5).slice(0, count);

    for (let i = 0; i < selected.length; i++) {
      const unit = selected[i];
      const features = {
        rampAccess: Math.random() > 0.5,
        brailleBallots: Math.random() > 0.8,
        signLanguage: Math.random() > 0.85,
        assistiveTech: Math.random() > 0.6,
        accessibleToilet: Math.random() > 0.4,
      };

      const numBarriers = randomInt(0, 4);
      const barriers = [...BARRIERS].sort(() => Math.random() - 0.5).slice(0, numBarriers);

      const score = Object.values(features).filter(Boolean).length / 5 * 100 - numBarriers * 8;
      const overallScore = Math.max(0, Math.min(100, parseFloat(score.toFixed(1))));

      await db.accessibilityReport.create({
        data: {
          tenantId: tenant.id,
          pollingUnitId: unit.id,
          reportedById: users[i % users.length]?.id || 'unknown',
          features: JSON.stringify(features),
          barrierTypes: JSON.stringify(barriers),
          pwdVotersServed: randomInt(0, 15),
          pwdVotersTurnedAway: barriers.length > 2 ? randomInt(1, 8) : 0,
          overallScore,
          verified: Math.random() > 0.6,
          notes: barriers.length > 2 ? 'Critical accessibility gaps identified. Immediate remediation required.' : 'Minor improvements recommended.',
          createdAt: new Date(Date.now() - randomInt(30, 480) * 60000),
        },
      });
    }
    console.log(`  ${tenant.name}: ${count} accessibility reports`);
  }
}

// ═══════════════════════════════════════════════════════════
// Security Events
// ═══════════════════════════════════════════════════════════
async function seedSecurityEvents() {
  console.log('Seeding security events...');

  const EVENT_TYPES = ['LOGIN_SUCCESS', 'LOGIN_FAILED', 'SUSPICIOUS_ACTIVITY', 'BRUTE_FORCE', 'API_ABUSE', 'SESSION_EXPIRED', 'PERMISSION_CHANGE'];
  const DESCRIPTIONS = [
    'User logged in from new device fingerprint',
    'Failed login attempt with invalid credentials',
    'Unusual data export pattern detected — 500+ records in 2 minutes',
    'Multiple failed login attempts from same IP (12 in 5 minutes)',
    'API rate limit exceeded for /api/incidents endpoint',
    'Session expired after timeout — user re-authenticated',
    'Admin elevated FIELD_AGENT to TENANT_ADMIN role',
    'Login from IP outside whitelisted range',
    'Biometric profile mismatch — typing cadence deviation detected',
    'Certificate pinning validation failed on mobile client',
  ];

  for (const tenant of TENANTS) {
    const users = await db.user.findMany({ where: { tenantId: tenant.id }, select: { id: true } });

    for (let i = 0; i < 20; i++) {
      const eventType = pick(EVENT_TYPES);
      const severity = eventType === 'BRUTE_FORCE' ? 'CRITICAL' : eventType === 'SUSPICIOUS_ACTIVITY' ? 'WARNING' : 'INFO';

      await db.securityEvent.create({
        data: {
          tenantId: tenant.id,
          userId: users[i % users.length]?.id || null,
          eventType,
          severity,
          description: DESCRIPTIONS[i % DESCRIPTIONS.length],
          ipAddress: `192.168.${randomInt(1, 254)}.${randomInt(1, 254)}`,
          userAgent: 'Mozilla/5.0 (OmniVote Mobile/2.1)',
          metadata: JSON.stringify({ timestamp: new Date().toISOString(), source: 'system' }),
          resolved: Math.random() > 0.6,
          resolvedAt: Math.random() > 0.6 ? new Date(Date.now() - randomInt(5, 120) * 60000) : null,
          createdAt: new Date(Date.now() - randomInt(10, 480) * 60000),
        },
      });
    }
    console.log(`  ${tenant.name}: 20 security events`);
  }
}

// ═══════════════════════════════════════════════════════════
// Geofence Zones & Check-ins
// ═══════════════════════════════════════════════════════════
async function seedGeofence() {
  console.log('Seeding geofence zones...');

  const ZONES = [
    { name: 'Lagos Island Central', state: 'Lagos', lga: 'Lagos Island', lat: 6.4541, lng: 3.3947, r: 500 },
    { name: 'Kano Municipal HQ', state: 'Kano', lga: 'Kano Municipal', lat: 12.0022, lng: 8.5920, r: 800 },
    { name: 'Enugu Urban Zone A', state: 'Enugu', lga: 'Enugu North', lat: 6.4424, lng: 7.4930, r: 600 },
    { name: 'Abuja Central District', state: 'Abuja FCT', lga: 'AMAC', lat: 9.0579, lng: 7.4951, r: 1000 },
    { name: 'Rivers Port Harcourt Metro', state: 'Rivers', lga: 'Port Harcourt', lat: 4.8156, lng: 7.0498, r: 700 },
  ];

  for (const tenant of TENANTS) {
    const elections = await db.election.findMany({ where: { tenantId: tenant.id }, select: { id: true } });
    if (!elections.length) continue;
    const units = await db.pollingUnit.findMany({ where: { electionId: elections[0].id }, select: { id: true } });
    const agents = await db.user.findMany({ where: { tenantId: tenant.id, role: 'FIELD_AGENT' }, select: { id: true } });

    for (const z of ZONES) {
      const zone = await db.geofenceZone.create({
        data: {
          tenantId: tenant.id,
          name: z.name,
          state: z.state,
          lga: z.lga,
          centerLat: z.lat,
          centerLng: z.lng,
          radiusMeters: z.r,
          pollingUnitIds: JSON.stringify(units.slice(0, randomInt(3, 8)).map(u => u.id)),
          assignedAgentIds: JSON.stringify(agents.slice(0, randomInt(2, 5)).map(a => a.id)),
          isActive: true,
          checkInIntervalMin: randomInt(30, 120),
          maxMissedCheckIns: randomInt(2, 4),
        },
      });

      // Create check-ins for agents in this zone
      const zoneAgents = agents.slice(0, randomInt(2, 5));
      for (let j = 0; j < zoneAgents.length; j++) {
        const isInside = Math.random() > 0.2;
        await db.agentCheckIn.create({
          data: {
            tenantId: tenant.id,
            agentId: zoneAgents[j].id,
            geofenceZoneId: zone.id,
            latitude: z.lat + (Math.random() - 0.5) * 0.01,
            longitude: z.lng + (Math.random() - 0.5) * 0.01,
            isInsideZone: isInside,
            batteryLevel: randomInt(15, 100),
            networkType: pick(['4G', '3G', 'WiFi', '2G']),
            accuracyMeters: randomFloat(5, 50),
            status: isInside ? 'CHECKED_IN' : (Math.random() > 0.9 ? 'SOS_TRIGGERED' : 'CHECKED_OUT'),
            checkedInAt: new Date(Date.now() - randomInt(5, 120) * 60000),
          },
        });
      }

      // Create dead-man's switches for agents
      for (let j = 0; j < Math.min(3, zoneAgents.length); j++) {
        const isOverdue = Math.random() > 0.6;
        await db.deadMansSwitch.create({
          data: {
            tenantId: tenant.id,
            agentId: zoneAgents[j].id,
            geofenceZoneId: zone.id,
            isActive: !isOverdue,
            checkInDeadline: new Date(Date.now() + (isOverdue ? -randomInt(10, 60) : randomInt(20, 90)) * 60000),
            lastCheckInAt: new Date(Date.now() - randomInt(30, 180) * 60000),
            missedCheckIns: isOverdue ? randomInt(1, 3) : 0,
            escalationLevel: isOverdue ? randomInt(1, 3) : 0,
            autoSOSTriggered: isOverdue && Math.random() > 0.5,
          },
        });
      }
    }
    console.log(`  ${tenant.name}: ${ZONES.length} zones with check-ins and switches`);
  }
}

// ═══════════════════════════════════════════════════════════
// Main
// ═══════════════════════════════════════════════════════════
async function main() {
  console.log('=== Seeding Election Day Operations Modules ===\n');
  await loadTenants();

  await seedPvt();
  await seedComparisons();
  await seedEvidence();
  await seedHoneypots();
  await seedFlashpoints();
  await seedAccessibility();
  await seedSecurityEvents();
  await seedGeofence();

  console.log('\n=== All election day modules seeded successfully ===');
}

main()
  .catch(console.error)
  .finally(() => process.exit(0));